project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "March Madness Bracket"
  description: "My Bracket Predictions!"
  site-url: https://catherinecjackson.github.io/march-madness/
  open-graph: true
  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source on GitHub](https://github.com/catherinecjackson/march-madness)
    center: |
      **Page still under construction.**
  sidebar:
    contents:
      - text: "Home"
        href: "index.qmd"
      - text: "Code"
        href: "test.qmd"

echo: true

format:
  html:
    theme: lux
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: document
    citations-hover: true
    code-annotations: hover
    code-line-numbers: true
    html-math-method: mathjax
    include-in-header: mathjax-config.html
    date-format: "ddd., MMM. D"
  revealjs:
    theme: _assets/sass/slides.scss
    slide-number: c/t
    show-slide-number: all
    hash-type: number
    center-title-slide: true
    width: 1280
    height: 720
    transition: none
    toc: false
    history: false
    menu:
      numbers: true
    scrollable: true
    preview-links: auto
    link-external-newwindow: true
    citations-hover: true
    code-annotations: below
    html-math-method: mathjax
    include-in-header: lectures/mathjax-config.html
    date-format: "ddd., MMM. D"

jupyter: julia-1.10
execute:
  freeze: auto
  cache: true

