name: Render Quarto Documents

on:
  push:
    branches:
      - main  # Or your default branch, if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Quarto
        uses: rspatial/quarto-setup@v2

      - name: Render Quarto Document
        run: quarto render index.qmd

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .  # Folder the HTML is in. Adjust if your output is in a different folder
